Added a Home Screen and the ability to add tasks
Flutter-Buddies/U-DO pull request #9
Opened 2021-04-06 04:31 UTC by Rift3000

2021-04-06 18:50 UTC, hanskokx requested changes
I didn't try compiling and running this - I'm making the assumption that you wouldn't push it if it didn't compile.

2021-04-06 18:50 UTC, hanskokx commented on lib/models/task.dart
> +  TaskList({this.title, this.taskIcon});
If `title` is empty, this will fail.  Mark `title` as required.

2021-04-06 18:50 UTC, hanskokx commented on lib/models/task_home_data.dart
> +    TaskList(title: "Han's Corner", taskIcon: Icon(Icons.run_circle)),
Han's => Hans'

2021-04-06 18:50 UTC, hanskokx commented on lib/models/task_home_data.dart
> +    final task = TaskList(title: myTaskTitle);
Will you add the `taskIcon` later?

2021-04-06 18:50 UTC, hanskokx commented on lib/screens/add_task_screen.dart
> +              style: TextButton.styleFrom(backgroundColor: Colors.lightBlue),
Nit: Perhaps the color should be specified in a global theme?  Then you can use `Theme.of(context).xxxx`

2021-04-06 18:50 UTC, hanskokx commented on lib/screens/home.dart
> +                                      MediaQuery.of(context).size.width / 20,
This seems like a dangerous calculation.  Maybe set a minimum, and use a `Wrap()`?

2021-04-06 18:50 UTC, hanskokx commented on lib/screens/home.dart
> +              fontSize: MediaQuery.of(context).size.width / 20,
Same here

2021-04-06 18:50 UTC, hanskokx commented on lib/screens/home.dart
> +            print(newTitle);
Don't forget to remove debugging statements

2021-04-06 18:50 UTC, hanskokx commented on lib/screens/home.dart
> +            Provider.of<TaskListHome>(context, listen: false).addTask(title);
If this fails for some reason, we'll still pop.  Might want to introduce some additional error handling, especially if this ends up pushing to a network resource (which may be unavailable)

2021-04-07 02:20 UTC, Rift3000 commented on lib/models/task.dart
> +  TaskList({this.title, this.taskIcon});
Good point

2021-04-07 02:20 UTC, Rift3000 commented on lib/models/task_home_data.dart
> +    TaskList(title: "Han's Corner", taskIcon: Icon(Icons.run_circle)),
ahh I see

2021-04-07 02:20 UTC, Rift3000 commented on lib/models/task_home_data.dart
> +    final task = TaskList(title: myTaskTitle);
I thinnk that is something that could be explored in the future. Allowing the user to select a task icon would be cool

2021-04-07 02:21 UTC, Rift3000 commented on lib/screens/add_task_screen.dart
> +              style: TextButton.styleFrom(backgroundColor: Colors.lightBlue),
mmhhnnn you smart

2021-04-07 02:22 UTC, Rift3000 commented on lib/screens/home.dart
> +                                      MediaQuery.of(context).size.width / 20,
Set it to a minimum? what do you mean?

2021-04-07 02:22 UTC, Rift3000 commented on lib/screens/home.dart
> +            print(newTitle);
totally forgot

2021-04-07 02:51 UTC, hanskokx commented on lib/screens/home.dart
> +                                      MediaQuery.of(context).size.width / 20,
Right now, the screen size always determines the font size. If someone happens to have a very small screen, the text could be size 2.  Just do a simple if statement. If the resulting font size is smaller than ~10, use a font size of 10. Otherwise, make sure you are using a whole number.

2021-04-07 18:26 UTC, Rift3000 commented
I addressed all the issues you highlighted and added two images to the Readme to show a little progress. Issues touched: Error handling, using ThemeData, debugging statements removed, etc. Currently don't see the need to add a wrap. We could possibly add it or review in the future.

2021-04-08 16:00 UTC, hanskokx approved these changes
Tiny changes, but otherwise looks good.

2021-04-08 16:00 UTC, hanskokx commented on lib/screens/home.dart
> +      backgroundColor: Colors.purple,
Maybe pull from the theme?

2021-04-08 16:00 UTC, hanskokx commented on lib/screens/home.dart
> +                  style: TextStyle(color: Colors.black, fontSize: 20.0),
Theme?

2021-04-08 16:00 UTC, hanskokx commented on lib/screens/home.dart
> +                      fillColor: Colors.white,
Theme?....you get the idea....

2021-04-08 16:17 UTC, Rift3000 commented on lib/screens/home.dart
> +                      fillColor: Colors.white,
lol Really not seeing the point of changing every color to use theme. Enlighten me

2021-04-08 16:20 UTC, hanskokx commented on lib/screens/home.dart
> +                      fillColor: Colors.white,
Light mode vs Dark mode

2021-04-08 16:29 UTC, Rift3000 commented on lib/screens/home.dart
> +                      fillColor: Colors.white,
Makes sense. Adding a dark mode later would be cool

2021-04-08 17:09 UTC, hanskokx commented on lib/screens/home.dart
> +                      fillColor: Colors.white,
Also, it keeps things consistent. If all the text should be the same color, using a shared variable saves time and effort when you want to change it.

2021-04-09 00:35 UTC, Rift3000 commented on lib/screens/home.dart
> +                      fillColor: Colors.white,
Ok, I used Theme

2021-04-09 00:48 UTC, hanskokx requested changes
So close! You can do it, Jason! 📣

2021-04-09 00:48 UTC, hanskokx commented on lib/screens/home.dart
> +        backgroundColor: Colors.lightBlueAccent,
Theme 😅

2021-04-09 00:48 UTC, hanskokx commented on lib/screens/home.dart
> +                  cursorColor: Colors.black,
🤔

2021-04-09 00:48 UTC, hanskokx commented on lib/screens/home.dart
> +                                color: Colors.red,
... I'll accept it

2021-04-09 00:48 UTC, hanskokx commented on lib/screens/home.dart
> +                              color: Colors.white,
🤔

2021-04-09 00:48 UTC, hanskokx commented on lib/screens/home.dart
> +                  primary: Colors.lightBlue,
🤔

2021-04-09 00:48 UTC, hanskokx commented on lib/screens/home.dart
> +                  style: TextStyle(color: Colors.white, fontSize: 20.0)),
🤔

2021-04-09 01:29 UTC, Rift3000 commented on lib/screens/home.dart
> +        backgroundColor: Colors.lightBlueAccent,
HOW did I miss these!!! LOL

2021-04-09 01:35 UTC, hanskokx commented on lib/screens/home.dart
> +        backgroundColor: Colors.lightBlueAccent,
n00b

2021-04-09 01:40 UTC, Rift3000 commented on lib/screens/home.dart
> +        backgroundColor: Colors.lightBlueAccent,
lol..... takes one to know one.....

2021-04-09 01:40 UTC, Rift3000 commented
This time for sure! None escaped my sight

2021-04-09 01:54 UTC, hanskokx approved these changes

2021-04-09 02:09 UTC, Rift3000 commented
Why not merge the pull request

2021-04-09 16:04 UTC, hanskokx commented
> Why not merge the pull request

Because I don't have permissions on this repo 🤷🏻‍♂️

2021-04-09 16:21 UTC, merged